### ISSUE TITLE
Plans for the future?

### ISSUE THREAD

**Issue by analyserdmz** [webtor-io/platform-sdk-js#37]
Hello! Thank you for this project!
Do you plan to keep it up for free in the future? Can we rely on your webtor servers?

If not, is there any paid plan available?

**Comment by vintikzzz** [comment]
Hi @analyserdmz 

There are several ways to use webtor:
1. [embed-sdk-js](https://github.com/webtor-io/embed-sdk-js) - the easiest free solution to start streaming torrent-content on your site. It embeds webtor.io player and uses webtor servers.
2. [platform-sdk-js](https://github.com/webtor-io/platform-sdk-js) (you are here!) - with this you can build your own player on your own webtor backend instance.
3. [helm-charts](https://github.com/webtor-io/helm-charts) - this can be used to setup you own webtor backend instance.

All variants are free to use and this is not going to change.
Currently I am also working on providing some paid API through [RapidAPI](https://rapidapi.com/).

**Comment by analyserdmz** [comment]
@vintikzzz thank you for this fantastic project! I really wish you the best with the paid API! Thanks for sharing this project, it's a life saver!
