### ISSUE TITLE
Can't push torrent into webtor service

### ISSUE THREAD

**Issue by wlasser** [webtor-io/platform-sdk-js#4]
Ok. Here is:
```
 kubectl get po -n webtor
NAME                                READY   STATUS    RESTARTS   AGE
content-prober-ddcfcf847-h8c2s      1/1     Running   2          21h
external-proxy-6c6989656-fwwgh      1/1     Running   0          21h
magnet2torrent-5df84c855-9t9m2      1/1     Running   0          21h
redis-master-0                      1/1     Running   0          21h
srt2vtt-67b77758d4-mzrxc            1/1     Running   0          21h
torrent-archiver-8475fb495b-l56xz   1/1     Running   0          21h
torrent-http-proxy-62x8x            1/1     Running   0          21h
torrent-store-65c6bd4659-dbq86      1/1     Running   1          21h
video-info-tn8pr                    1/1     Running   0          21h
```
And 
```
minikube service torrent-http-proxy --url -n webtor
http://xxx:30604
http://xxx:32343
```
I don't understand why is there two api links.

But next:

```
 curl -I  http://xxx:30604
HTTP/1.1 500 Internal Server Error
Date: Sun, 22 Mar 2020 09:07:53 GMT

curl -I  http://xxx:32343
curl: (8) Weird server reply
```
And JS console:
`Uncaught (in promise) failed to push torrent code=14`

Thank you.

**Comment by wlasser** [comment]
is it normal?
`---|
|  NAMESPACE  |        NAME        | TARGET PORT  |              URL               |
|-------------|--------------------|--------------|--------------------------------|
| default     | kubernetes         | No node port |
| kube-system | kube-dns           | No node port |
| kube-system | tiller-deploy      | No node port |
| webtor      | content-prober     | No node port |
| webtor      | external-proxy     | No node port |
| webtor      | magnet2torrent     | No node port |
| webtor      | redis-headless     | No node port |
| webtor      | redis-master       | No node port |
| webtor      | srt2vtt            | No node port |
| webtor      | torrent-archiver   | No node port |
| webtor      | torrent-http-proxy |              | http://185.242.84.84:30604     |
|             |                    |              | http://185.242.84.84:32343     |
| webtor      | torrent-store      | No node port |
| webtor      | video-info         | No node port |
|-------------|--------------------|--------------|-----------------------------`

**Comment by wlasser** [comment]
Any tips, solutions, advices?

**Comment by wlasser** [comment]
Ok. Reboot all, make clean install of services and... it's don. Thank you!

**Comment by vintikzzz** [comment]
Great! Sorry for not answering in time...
