### ISSUE TITLE
CORS configuration

### ISSUE THREAD

**Issue by melhirech** [webtor-io/platform-sdk-js#40]
Hello sir, I would like to thank you for this work.

I've install helm-charts backend on my VPS, it's running correctly. Now I'm trying to run the example provided in this repo but I'm getting CORS issues.

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://x.x.x.x:30180//store/TorrentStore/Pull. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)`

I can't find where I can add CORS config. Is there a server config file that I need to be aware of?

Thank you in advance for your help and support.

**Comment by vintikzzz** [comment]
Hi @melhirech !
Do you use any proxy servers?
Currently API should return `access-control-allow-origin: *` to allow cross-origin request.
No additional configuration needed.

**Comment by melhirech** [comment]
Thank you @vintikzzz for taking the time to debug the issue with me. As you've pointed out, I had an extra slash '/' at the end of my apiUrl which caused this issue. This has nothing to do with CORS config.

Closing this issue.
