### ISSUE TITLE
Download zip file is not working

### ISSUE THREAD

**Issue by wlasser** [webtor-io/platform-sdk-js#5]
Maybe this my misstake, maybe this need additional software like unzip, p7zip or something?
When i am get the zip url, this give empty archive.

**Comment by wlasser** [comment]
And litle trouble with getting streaming url.
For transcoding content(mkv for me) - service is give streaming url with ~hls/index.m3u8, but this link give translation from current streaming position, and i can't start from beginning. But this is possible is just my missunderstanding of using this? Can you explain a litle bit for those items. Thank for you work!

**Comment by vintikzzz** [comment]
For the first question about zip:
You don't need any additional software. Can you provide code snippet?
For the second question about HLS:
It all depends on your HLS-player. Some of them fast forward to the latest fragment, some of them note. Anyway, service generates `index.m3u8` with all transcoded fragments and automatically updates it when new available.

**Comment by wlasser** [comment]
`const zipUrl = await seeder.zipUrl(filePath);`

**Comment by vintikzzz** [comment]
`filePath` should point to folder in torrent.
To download whole content of demo torrent with Sintel movie you should
```
const filePath = '/Sintel';
const zipUrl = await seeder.zipUrl(filePath);
``` 
This archives `/Sintel` folder to `Sintel.zip`
`filePath` can't be empty like "/"
When it generates zip it cuts last subfolder in the `filePath` and uses it as zip archive name

**Comment by wlasser** [comment]
> `filePath` should point to folder in torrent.
> To download whole content of demo torrent with Sintel movie you should
> 
> ```
> const filePath = '/Sintel';
> const zipUrl = await seeder.zipUrl(filePath);
> ```
> 
> This archives `/Sintel` folder to `Sintel.zip`
> `filePath` can't be empty like "/"
> When it generates zip it cuts last subfolder in the `filePath` and uses it as zip archive name

ok, thanks will try it.

**Comment by wlasser** [comment]
I am try many ways, but can't zip torrent. If torrent doesn't have directory, what i must to do for make zip url for torrent without directory? how to get root?

**Comment by vintikzzz** [comment]
Sorry... But it is not possible to zip single-file torrent. You can just download this file directly. Currently archiving is only used for packaging multi-file torrents in one file. There is no compression at all. Can you just describe your specific use-case?

**Comment by wlasser** [comment]
> Sorry... But it is not possible to zip single-file torrent. You can just download this file directly. Currently archiving is only used for packaging multi-file torrents in one file. There is no compression at all.

at some moment i am understood this. reading code sometime can be usefull, but javascript is a litle new for me and many places of code looks so hard, but just few minutes and it's just JS, and realy simple...



>  Can you just describe your specific use-case?

Oh, there is no something specific. Just testing and study new service. I think you must to do "wiki" with FAQ of all over it, because many stupid questions can be resolved by this.
And...
Now i am implement short code stuff to get file extension, for switching mediatypes, not much at all and this just few lines of code, but i want to do pull request. You are have no contributor info (or i am blind).
Anyway - thank you for all of tons work with webtor, there is so much ways to use this service.

**Comment by wlasser** [comment]
And another question:
As i am remember - browsers reject unencrypted websocket connection, if you are trying connect from https host to http websocket. Not tested yet with webtor, but await for bad news.
Is it?

**Comment by vintikzzz** [comment]
> Oh, there is no something specific. Just testing and study new service. I think you must to do "wiki" with FAQ of all over it, because many stupid questions can be resolved by this.

It is really good idea. I was already thinking about it. 

> Now i am implement short code stuff to get file extension, for switching mediatypes, not much at all and this just few lines of code, but i want to do pull request.

Some code is already there
https://github.com/webtor-io/platform-sdk-js/blob/2c2e2f8277182ffdecae1d12df0537503278ddcd/src/sdk/util.js#L32

> You are have no contributor info (or i am blind).

You can find them [here](https://github.com/webtor-io/platform-sdk-js/graphs/contributors)

> As i am remember - browsers reject unencrypted websocket connection, if you are trying connect from https host to http websocket. Not tested yet with webtor, but await for bad news.
Is it?

There is no such problem if you are trying to call unencrypted websocket from http. I have tested it plenty of times with Chrome browser during development. But in production you should do ssl-encryption.

**Comment by wlasser** [comment]
> But in production you should do ssl-encryption.

any advice to proxy connection to torrent-http-proxy? Now googling and googling again and againm and no found anything usefull.

> You can find them [here](https://github.com/webtor-io/platform-sdk-js/graphs/contributors)

i am about code-style, pull-request templates and other.

**Comment by wlasser** [comment]
well. this is now resolved. damn, i am sweat with it, but... magic. You can use this config for NGINX like example in WIKI or HowTo or FAQ.
Thank you, again.
```

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
 server {
    server_name youdomain.com;
	ssl on;
	listen 9999;
    location / {
	
                proxy_pass http://webtor-backend;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_http_version 1.1;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_intercept_errors on;
                proxy_redirect off;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-NginX-Proxy true;
                proxy_ssl_session_reuse off;  
    }
    
    ssl_certificate /etc/letsencrypt/live/youdomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/youdomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

  upstream webtor-backend{
    # enable sticky session based on IP
    ip_hash;

    server %webtor-http-proxy-url%;
  }
```
**Affter this you  must change api url to https://youdomain.com:9999**

**Comment by vintikzzz** [comment]
If you use kubernetes cloud provider it is better to use `nginx-ingress-controller` with 'cert-manager'

**Comment by wlasser** [comment]
> If you use kubernetes cloud provider it is better to use `nginx-ingress-controller` with `cert-manager`

Ok. Thank you. The microservice stuff is very new for me and many  things looks mad. But live for century - learn for century.
You can close this issue. Thanks again.
