### ISSUE TITLE
Question about api

### ISSUE THREAD

**Issue by FedeJure** [webtor-io/platform-sdk-js#7]
Hi!! nice work with this!! 
i have a little question.
which api do you mean in the configurations?? there is a repo?? the only way is to use https://webtor.io?? thankyou!!!

**Comment by FedeJure** [comment]
Sry, i was confused, you mean to this api https://github.com/webtor-io/helm-charts isit? thanks!

**Comment by vintikzzz** [comment]
Yes! You are right!
